#!/bin/bash
# ==============================================================================
# Start the SPC Web Gateway service
# s6-overlay docs: https://github.com/just-containers/s6-overlay
# ==============================================================================

# bashio does not work on Ubuntu 18 - I guess it needs a bash version 5 (ver 4 for Ubuntu 18)
echo "start"

## Install the package if not installed already
# Install SPC gateway stuff
if [ ! -d "/opt/spc-web-gateway" ]; then
  cd /tmp
  tar -zxf /config/spc-web-gateway-ubuntu_x86_64_18_04.1.5.tar.gz
  cd spc-web-gateway-1.5

  echo "Installing SPC Web Gateway files"

  INSTALL_DIR=/opt/spc-web-gateway

  install -m 755 -p -d ${INSTALL_DIR}
  install -m 755 -p spc-web-gateway ${INSTALL_DIR}
  install -m 644 -p config.xml ${INSTALL_DIR}
  install -m 644 -p SPC_WEB_GATEWAY_EULA.txt ${INSTALL_DIR}
  install -m 644 -p VERSION ${INSTALL_DIR}

  install -m 755 -p -d ${INSTALL_DIR}/auth
  install -m 644 -p auth/edp_key ${INSTALL_DIR}/auth
  install -m 644 -p auth/passwd_get ${INSTALL_DIR}/auth
  install -m 644 -p auth/passwd_put ${INSTALL_DIR}/auth
  install -m 644 -p auth/passwd_ws ${INSTALL_DIR}/auth
  install -m 644 -p auth/ssl_certificate.pem ${INSTALL_DIR}/auth
  install -m 644 -p auth/license ${INSTALL_DIR}/auth

  install -m 755 -p -d ${INSTALL_DIR}/www
  install -m 644 -p www/index.html ${INSTALL_DIR}/www

fi


## Copy settings to config.xml
options=/data/options.json
config=/opt/spc-web-gateway/config.xml

xmlstarlet edit --inplace \
  --update "//config//enable_get_auth" --value "no" \
  --update "//config//enable_put_auth" --value "no" \
  --update "//config//enable_ws_auth" --value "no" \
  --update "//config//enable_ssl_encryption" --value "no" \
  --update "//config//spc_id" --value $(jq '.spc_id' $options) \
  --update "//config//gateway_id" --value $(jq '.gateway_id' $options) \
  --update "//config//access_control_list" --value "" \
  $config

get_user=$(jq '.get_user' $options)
put_user=$(jq '.put_user' $options)
ws_user=$(jq '.ws_user' $options)
get_password=$(jq '.get_password' $options)
put_password=$(jq '.put_password' $options)
ws_password=$(jq '.ws_password' $options)

echo $get_user

## Generate auth data
expect -c "spawn /opt/spc-web-gateway/spc-web-gateway -A
expect \"Username*\"
send $get_user
send \"\r\"
expect \"New password: \"
send $get_password
send \"\r\"
expect \"Re-type password: \"
send $get_password
send \"\r\"
expect \"Username*\"
send $put_user
send \"\r\"
expect \"New password: \"
send $put_password
send \"\r\"
expect \"Re-type password: \"
send $put_password
send \"\r\"
expect \"Username*\"
send $ws_user
send \"\r\"
expect \"New password: \"
send $ws_password
send \"\r\"
expect \"Re-type password: \"
send $ws_password
send \"\r\"
expect \"EDP encryption key (32 hexadecimal digits): \"
send $(jq '.encryption_key' $options)
send \"\r\"
expect eof"

## Run program
runuser -u spc -- /opt/spc-web-gateway/spc-web-gateway

