name: SPC Web Gateway
version: "1.0.0"
slug: spc-web-gateway
description: Run the SPC Web Gateway from Lundix IT
url: "https://github.com/martin67/home-assistant-addons/tree/main/spc-web-gateway"
arch:
  - amd64
init: false
apparmor: false
map:
  - addon_config
webui: http://[HOST]:[PORT:8088]
ports:
  16000/tcp: 16000
  8088/tcp: 8088
ports_description:
  16000/tcp: "EDP receiver port"
  8088/tcp: "Port to listen on for web client connections."
options:
  spc_id: 1000
  gateway_id: 1000
  receiver_port: 16000
  enable_get_auth: false
  enable_put_auth: false
  enable_ws_auth: false
  get_user: "get_user"
  get_password: "secret"
  put_user: "put_user"
  put_password: "secret"
  ws_user: "ws_user"
  ws_password: "secret"
  encryption_key: "00112233445566778899AABBCCDDEEFF"
schema:
  spc_id: int(1,999997)
  gateway_id: int(1,999997)
  receiver_port: port
  enable_get_auth: bool
  enable_put_auth: bool
  enable_ws_auth: bool
  get_user: str
  get_password: str
  put_user: str
  put_password: str
  ws_user: str
  ws_password: str
  encryption_key: str
#image: "ghcr.io/home-assistant/{arch}-addon-example"
