# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: SPC Web Gateway add-on
version: "1.0.0"
slug: spc-web-gateway
description: SPC Web Gateway add-on
url: "https://github.com/martin67/home-assistant-addons/tree/main/spc-web-gateway"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  edp_panel_id: 1000
  receiver_id: 1000
  receiver_port: 16000
  encryption_key: null
schema:
  edp_panel_id: int(1,999997)
  receiver_id: int(1,999997)
  receiver_port: port
  encryption_key: str
#image: "ghcr.io/home-assistant/{arch}-addon-example"
